@url = http://127.0.0.1:3001
@id=28db822a-9f57-4572-b23a-e10ec3cf9c82

//Gets
###
GET {{url}}/doencas/{{id}} HTTP/1.1
Accept: application/json
###
GET {{url}}/doencas/plantas/{{id}} HTTP/1.1
Accept: application/json

###
//Posts
POST {{url}}/doencas HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nome": "dodoi4",
    "transmissao": "solo",
    "prevencao": "parar de ser otario2",
    "tratamento": "agrotoxico"
}

###
//findAll
GET {{url}}/doencas HTTP/1.1
Accept: application/json

###
//Update
PUT {{url}}/doencas/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nome": "dodoi10",
    "transmissao": "solo",
    "prevencao": "parar de ser otario5",
    "tratamento": "agrotoxico"
}
###
//Deletes
###
DELETE {{url}}/doencas/{{id}} HTTP/1.1
Accept: application/json