@url = http://127.0.0.1:3001
@doenca_id=28db822a-9f57-4572-b23a-e10ec3cf9c82

@id=9064ec25-105d-4c45-86ef-8c3ecd764884

//Gets
GET {{url}}/plantas HTTP/1.1
Accept: application/json

###
//Create
POST {{url}}/plantas
Content-Type: application/json
Accept: application/json

{
   "nome": "plantinha",
   "especie": "",
   "tecnicas_plantio": "Semeadura",
   "infos_por_estacao": "Verão",
   "cor_folhas": "Verde",
   "num_frutos_colhidos": 10,
   "qtd_diaria_agua": 2.5,
   "qtd_media_sementes": 30,
   "nivel_incidencia_solar": 5.5
}

###
//FindAll
GET {{url}}/plantas HTTP/1.1
Accept: application/json

###
//Update
PUT {{url}}/plantas/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "nome": "Milho10",
   "especie": "True",
   "tecnicas_plantio": "Semeadura",
   "infos_por_estacao": "Inverno",
   "cor_folhas": "Amarela",
   "num_frutos_colhidos": 15,
   "qtd_diaria_agua": 2.5,
   "qtd_media_sementes": 30,
   "nivel_incidencia_solar": 5.5
}
###
GET {{url}}/plantas/doencas/{{id}}/{{doenca_id}} HTTP/1.1
Accept: application/json
###
GET {{url}}/plantas/{{id}} HTTP/1.1
Accept: application/json
###
GET {{url}}/plantas/doencas/{{id}} HTTP/1.1
Accept: application/json
//Deletes
###
DELETE {{url}}/plantas/{{id}} HTTP/1.1
Accept: application/json
###
DELETE {{url}}/plantas/doencas/{{id}}/{{doenca_id}} HTTP/1.1
Accept: application/json
// PUTS
###
PUT {{url}}/plantas/doencas/{{id}}/{{doenca_id}} HTTP/1.1
Accept: application/json
