@url = http://127.0.0.1:3001
@id=70b1cc0f-986a-4102-85c4-aae5acca7de8
@planta_id=b15783e1-5473-4664-9def-ebc882dbe8de

//Gets
GET {{url}}/plantacoes/{{id}} HTTP/1.1
Accept: application/json
###
//Posts
POST {{url}}/plantacoes HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "solo_id": "1112beab-fab9-4ae5-ab87-8844733dcfb4" 
}
###
// DELETES
DELETE {{url}}/plantacoes/{{id}} HTTP/1.1
Accept: application/json

// PUTS
###
PUT {{url}}/plantacoes/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "solo_id": "b49c1bb8-fea8-4070-b589-dc00c0aa40b0" 
}
###
PUT {{url}}/plantacoes/{{id}}/{{planta_id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

###
//FindAll
GET {{url}}/plantacoes HTTP/1.1
Accept: application/json