@url = http://127.0.0.1:3001
@id=b9b924d3-4977-4b2e-8d11-2d041d232a48
@planta_id=0498a289-fa88-4d7e-9c19-6519c620300b
@solo_id=36cbedd5-3d47-4e8f-b052-a95dae4a8b58

//Gets
GET {{url}}/plantacoes/{{id}} HTTP/1.1
Accept: application/json
###
GET {{url}}/plantacoes/plantas/{{id}} HTTP/1.1
Accept: application/json
###
GET {{url}}/plantacoes/plantas/{{id}}/{{planta_id}} HTTP/1.1
Accept: application/json
###
GET {{url}}/plantacoes/solos/{{id}}/{{solo_id}} HTTP/1.1
Accept: application/json
###
//Posts
POST {{url}}/plantacoes HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "solo_id": "{{solo_id}}"
}
###
DELETE {{url}}/plantacoes/{{id}} HTTP/1.1
Accept: application/json
###
// DELETES
DELETE {{url}}/plantacoes/plantas/{{id}}/{{planta_id}} HTTP/1.1
Accept: application/json

// PUTS
###
PUT {{url}}/plantacoes/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "solo_id": "b49c1bb8-fea8-4070-b589-dc00c0aa40b0" 
}
###
PUT {{url}}/plantacoes/{{id}}/{{planta_id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

###
//FindAll
GET {{url}}/plantacoes HTTP/1.1
Accept: application/json