@url = http://127.0.0.1:3001
@id =  36981c8f-0d61-455b-ae83-ed11f3aeb380

//Gets

###
//Posts
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.0,
    "tipo_solo": "TIPOB",
    "prevencao": "tralala",
    "temperatura": 39.6,
    "tipo_vaso": "TIPOA"
}
###
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 5.8,
    "tipo_solo": "TIPOA",
    "prevencao": "tralala2",
    "temperatura": 35.2,
    "tipo_vaso": "TIPOB"
}
###
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 3.2,
    "tipo_solo": "TIPOC",
    "prevencao": "tralala3",
    "temperatura": 17.7,
    "tipo_vaso": "TIPOA"
}
###
// Puts
PUT {{url}}/solos/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.2,
    "tipo_solo": "TIPOC",
    "prevencao": "blabla",
    "temperatura": 36.2,
    "tipo_vaso": "TIPOB"
}

###
// Deletes
DELETE {{url}}/solos/{{id}} HTTP/1.1
Accept: application/json

###
//FindAll
GET {{url}}/solos HTTP/1.1
Accept: application/json
