@url = http://127.0.0.1:3001
@id = 96339301-1e24-4f8c-ac8f-9e31ba174eb0

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMzQ0OWNlZTUtYTFhZi00ZTUyLWJiNzEtMzE5MDdmOTU0MTk4IiwiZW1haWwiOiJsb3d2YTk2QGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZX0sImlhdCI6MTYzMjg3NjExNSwiZXhwIjoxNjMyODc2NDE1fQ.RFt92zWoZglg3JOu-YmeZjFVsHXcXFvNDSzVhXuicNM

//Gets

###
//Posts
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "nivel_ph": 6.0,
    "tipo_solo": "TIPOB",
    "temperatura": 39.6,
    "tipo_vaso": "TIPOA"
}
###
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 5.8,
    "tipo_solo": "TIPOA",
    "temperatura": 35.2,
    "tipo_vaso": "TIPOB"
}
###
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 7.0,
    "tipo_solo": "TIPOA",
    "temperatura": 39.9,
    "tipo_vaso": "TIPOB"
}
###
// Puts
PUT {{url}}/solos/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.2,
    "tipo_solo": "TIPOC",
    "temperatura": 36.2,
    "tipo_vaso": "TIPOB"
}

###
// Deletes
DELETE {{url}}/solos/{{id}} HTTP/1.1
Accept: application/json

###
//FindAll
GET {{url}}/solos?size=2&page=0 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}
###
GET {{url}}/solos/{{id}} HTTP/1.1
Accept: application/json
