@url = http://127.0.0.1:3001
@id = 4ba2c700-5c5c-473d-b0c8-aff79e36c4d4
// 36cbedd5-3d47-4e8f-b052-a95dae4a8b58

//Gets

###
//Posts
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.0,
    "tipo_solo": "TIPOB",
    "temperatura": 39.6,
    "tipo_vaso": "TIPOA"
}
###
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 5.8,
    "tipo_solo": "TIPOA",
    "temperatura": 35.2,
    "tipo_vaso": "TIPOB"
}
###
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 7.0,
    "tipo_solo": "TIPOA",
    "temperatura": 39.9
    // "tipo_vaso": "TIPOB"
}
###
// Puts
PUT {{url}}/solos/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.2,
    "tipo_solo": "TIPOC",
    "temperatura": 36.2,
    "tipo_vaso": "TIPOB"
}

###
// Deletes
DELETE {{url}}/solos/{{id}} HTTP/1.1
Accept: application/json

###
//FindAll
GET {{url}}/solos HTTP/1.1
Accept: application/json
###
GET {{url}}/solos/{{id}} HTTP/1.1
Accept: application/json
