@url = http://127.0.0.1:3001
@id = 2bcced3d-7d9f-4de5-88e3-7a57f0c1b039
@senha = $2b$10$FeY4k68nkS8KKCIO4vAqFuq3CAXVaCJsQKNZ.Wj5PMAK.nZwlrRU.
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZWQyZTVjZTktZjEzMS00YzkxLWIyMjUtMGM3OWU3MDczZTM5IiwiZW1haWwiOiJkb2NpbmhvQGhvdG1haWwuY29tIiwiaXNfYWRtaW4iOnRydWV9LCJpYXQiOjE2MzEyMjU0NDksImV4cCI6MTYzMTIyNTc0OX0.heXUfArCaE-oxNfq-oEd8qDuAWGxGyFJk3G76ofsfAs

###
//Posts
POST {{url}}/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "docinho@hotmail.com",
    "nome": "Docinho",
    "senha": "something"
}
###
POST {{url}}/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "docinho@hotmail.com",
    "senha": "something"
}
###
GET {{url}}/authProtected HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}
